# -*- coding: utf-8 -*-
"""rekomendasi_barang.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/github/heriswaya/MLT-Project-1-and-2/blob/main/rekomendasi_barang.ipynb

## **Import Library**
"""

import pandas as pd
import numpy as np
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import layers
from sklearn.model_selection import train_test_split
import matplotlib.pyplot as plt

import warnings
warnings.filterwarnings('ignore')

"""## **Data Understanding**"""

# Unduh file zip dari GitHub
!wget https://github.com/heriswaya/MLT-Project-1-and-2/raw/main/dataset_recommendation/archive.zip

# Ekstrak file zip
!unzip archive.zip

"""Terdapat 6 file csv. <br>
Untuk membangun model Collaborative Filtering, hanya perlu menggunakan file-file yang mengandung interaksi eksplisit atau implisit antara user dan item. Berikut file yang akan digunakan:
Untuk membangun model **Collaborative Filtering**, Anda hanya perlu menggunakan file-file yang mengandung **interaksi eksplisit atau implisit antara user dan item**. Berikut rekomendasi file yang akan digunakan:
1. **`transactions.csv`**  
   - **Alasan**: Ini adalah data transaksi aktual yang menunjukkan pembelian produk oleh pelanggan.
   - **Kolom Penting**:
     - `customer_id` (User)
     - `product_name` (Item)
     - `quantity` (Implicit rating: bisa dianggap sebagai "strength of interaction")
     - `price` (Opsional: bisa digunakan untuk weighting)

2. **`customer_reviews_complete.csv`**  
   - **Alasan**: Berisi rating eksplisit (1-5) dari pelanggan.
   - **Kolom Penting**:
     - `customer_id` (User)
     - `product_name` (Item)
     - `rating` (Explicit rating)

3. **`interactions.csv`** (Opsional)  
   - **Alasan**: Bisa digunakan sebagai implicit feedback tambahan.
   - **Kolom Penting**:
     - `customer_id` (User)
     - `page_or_product` (Item)
     - `interaction_type` (e.g., "View Product" = 1 point, "Add to Cart" = 2 points, dll.)

### File yang Tidak Perlu Digunakan:
- `customers.csv` (Data demografi - lebih cocok untuk content-based, bukan collaborative)
- `campaigns.csv` (Info marketing - tidak relevan)
- `support_tickets.csv` (Data support - tidak relevan)
"""

# Membaca data-data yang relevan untuk collaborative filtering
transactions = pd.read_csv('/content/transactions.csv')
reviews = pd.read_csv('/content/customer_reviews_complete.csv')
interactions = pd.read_csv('/content/interactions.csv')
customers = pd.read_csv('/content/customers.csv')  # Untuk referensi saja

transactions.head()

reviews.head()

interactions.head()

customers.head()

print('Jumlah data pelanggan unik: ', len(customers.customer_id.unique()))
print('Jumlah produk unik yang dibeli: ', len(transactions.product_name.unique()))
print('Jumlah transaksi: ', len(transactions))
print('Jumlah rating/review: ', len(reviews))
print('Jumlah interaksi pengguna: ', len(interactions))

print('\n=== DETAIL INTERAKSI ===')
print('Jumlah pelanggan yang memberikan rating: ', len(reviews.customer_id.unique()))
print('Jumlah produk yang mendapat rating: ', len(reviews.product_name.unique()))
print('Jumlah pelanggan yang berinteraksi: ', len(interactions.customer_id.unique()))
print('Jumlah produk yang diinteraksi: ', len(interactions.page_or_product.unique()))

print('\n=== DISTRIBUSI RATING ===')
print(reviews.rating.value_counts().sort_index())

"""## **Univariate Exploratory Data Analysis**

Penjelasan nama variabel yang digunakan:
- transactions: Data transaksi pembelian produk oleh pelanggan
- reviews: Data rating dan review produk oleh pelanggan
- interactions: Data interaksi pengguna dengan produk (view, click, dll)
- customers: Data profil pelanggan (digunakan hanya untuk referensi)

### Transactions
"""

print("📦 EDA: Transactions")
transactions.info()

print("\nJumlah transaksi:", transactions.shape[0])
print("Jumlah customer unik:", transactions['customer_id'].nunique())
print("Jumlah produk unik:", transactions['product_name'].nunique())
print("Jumlah kategori produk unik:", transactions['product_category'].nunique())

print("\nMetode pembayaran yang digunakan:", transactions['payment_method'].unique())
print("Jumlah metode pembayaran unik:", transactions['payment_method'].nunique())

print("\nCek data kosong:")
print(transactions.isnull().sum())

print("\nStatistik deskriptif kolom numerik:")
print(transactions[['quantity', 'price', 'discount_applied']].describe())

"""### Reviews"""

print("📝 EDA: Reviews")
reviews.info()

print("\nJumlah review:", reviews.shape[0])
print("Jumlah customer unik:", reviews['customer_id'].nunique())
print("Jumlah produk unik:", reviews['product_name'].nunique())
print("Jumlah kategori produk unik:", reviews['product_category'].nunique())

print("\nStatistik rating:")
print(reviews['rating'].describe())

print("\nDistribusi rating:")
print(reviews['rating'].value_counts().sort_index())

print("\nCek data kosong:")
print(reviews.isnull().sum())

"""### Interactions"""

print("🖱️ EDA: Interactions")
interactions.info()

print("\nJumlah interaksi:", interactions.shape[0])
print("Jumlah customer unik:", interactions['customer_id'].nunique())
print("Jumlah jenis interaksi unik:", interactions['interaction_type'].nunique())
print("Jumlah channel unik:", interactions['channel'].nunique())

print("\nJenis interaksi yang tersedia:")
print(interactions['interaction_type'].value_counts())

print("\nCek data kosong:")
print(interactions.isnull().sum())

print("\nStatistik durasi interaksi:")
print(interactions['duration'].describe())

"""### Customers"""

print("👤 EDA: Customers")
customers.info()

print("\nJumlah customer:", customers.shape[0])
print("Jumlah gender unik:", customers['gender'].nunique())
print("Jumlah kota unik:", customers['city'].nunique())
print("Jumlah channel pilihan unik:", customers['preferred_channel'].nunique())

print("\nDistribusi gender:")
print(customers['gender'].value_counts())

print("\nCek data kosong:")
print(customers.isnull().sum())

print("\nStatistik umur:")
print(customers['age'].describe())

"""## **Data Preprocessing**
Mengambil kolom-kolom penting dari tiap dataframe, lalu menggabungkan atau menyusun ulang data sehingga siap dibersihkan (di tahap berikutnya).

### Menggabungkan seluruh user–item–rating
"""

# Data utama: customer_id, product_name, rating
ratings_df = reviews[['customer_id', 'product_name', 'rating']].dropna()

print("Jumlah total interaksi rating:", ratings_df.shape[0])
print("Jumlah user unik:", ratings_df['customer_id'].nunique())
print("Jumlah produk unik:", ratings_df['product_name'].nunique())
ratings_df.head()

"""### Menggabungkan data produk"""

# Ambil data unik produk dari transactions
product_features = transactions[['product_name', 'product_category']].dropna().drop_duplicates()

# Gabungkan dengan data rating
ratings_df = ratings_df.merge(product_features, on='product_name', how='left')

ratings_df.head()

"""### Mengetahui jumlah rating per user dan per produk"""

# Rating per user
rating_per_user = ratings_df.groupby('customer_id').size().sort_values(ascending=False)
print("5 user dengan jumlah rating terbanyak:")
print(rating_per_user.head())

# Rating per produk
rating_per_product = ratings_df.groupby('product_name').size().sort_values(ascending=False)
print("\n5 produk dengan jumlah rating terbanyak:")
print(rating_per_product.head())

"""### Gabung nama pelanggan atau info lain (hanya untuk referensi UI / analisis)"""

# Tambahkan nama lengkap user dari reviews
user_names = reviews[['customer_id', 'full_name']].drop_duplicates()

# Gabungkan ke data rating
ratings_df = ratings_df.merge(user_names, on='customer_id', how='left')
ratings_df

# 1. Ambil daftar nama produk unik dari ratings_df
produk_terdaftar = ratings_df['product_name'].dropna().unique()

# 2. Filter interactions agar hanya yang page_or_product ada di daftar tersebut
filtered_interactions = interactions[interactions['page_or_product'].isin(produk_terdaftar)].copy()

# 3. Hitung interaction_score = jumlah interaksi per user per produk
interaction_score = (
    filtered_interactions
    .groupby(['customer_id', 'page_or_product'])
    .size()
    .reset_index(name='interaction_score')
)

# 4. Gabungkan ke ratings_df
ratings_with_interaction = ratings_df.merge(
    interaction_score,
    left_on=['customer_id', 'product_name'],
    right_on=['customer_id', 'page_or_product'],
    how='left'
)

# 5. Hilangkan kolom duplikat dan isi NaN dengan 0
ratings_with_interaction.drop(columns=['page_or_product'], inplace=True)
ratings_with_interaction['interaction_score'] = ratings_with_interaction['interaction_score'].fillna(0)

# Cek hasilnya
ratings_with_interaction

# Hitung jumlah baris dengan interaction_score > 0
jumlah_positif = (ratings_with_interaction['interaction_score'] > 0).sum()

# Total baris dalam ratings_with_interaction
total_baris = len(ratings_with_interaction)

# Hitung persentase
persentase = jumlah_positif / total_baris * 100

# Tampilkan hasil
print(f"Jumlah data dengan interaction_score > 0: {jumlah_positif} dari {total_baris} baris ({persentase:.2f}%)")

"""Meskipun hanya sekitar 5.84% data yang memiliki `interaction_score > 0`, data tersebut tetap bernilai tinggi, apalagi untuk model rekomendasi, karena mencerminkan perilaku nyata pengguna.

## **Data Preparation**
"""

# Membaca dataset
df = ratings_with_interaction
df

# Cek data missing
df.isnull().sum()

"""Biarkan saja `full_name` tetap kosong sebagian. Tidak perlu dihapus atau diisi karena tidak memengaruhi model."""

# Cek data duplikat
print("Banyak baris duplikat:", df.duplicated().sum())

# Hapus baris duplikat
df = df.drop_duplicates()
print("Banyak baris duplikat:", df.duplicated().sum())

# Mengecek kategori produk yang unik
df.product_category.unique()

"""Pada tahap ini, perlu dilakukan persiapan data untuk menyandikan (encode) fitur ‘user’ dan ‘placeID’ ke dalam indeks integer."""

# 1. Dapatkan list unik user dan produk
user_ids = df['customer_id'].unique().tolist()
product_ids = df['product_name'].unique().tolist()

# 2. Buat mapping encoding
user_to_user_encoded = {x: i for i, x in enumerate(user_ids)}
user_encoded_to_user = {i: x for i, x in enumerate(user_ids)}

product_to_product_encoded = {x: i for i, x in enumerate(product_ids)}
product_encoded_to_product = {i: x for i, x in enumerate(product_ids)}

# 3. Mapping ke dataframe
df['user'] = df['customer_id'].map(user_to_user_encoded)
df['product'] = df['product_name'].map(product_to_product_encoded)

# 4. Pastikan rating bertipe float32
df['rating'] = df['rating'].astype(np.float32)

# 5. Informasi jumlah dan skala rating
num_users = len(user_to_user_encoded)
num_products = len(product_to_product_encoded)

min_rating = df['rating'].min()
max_rating = df['rating'].max()

print(f"Jumlah User: {num_users}")
print(f"Jumlah Produk: {num_products}")
print(f"Skala Rating: {min_rating} hingga {max_rating}")

print('list userID: ', user_ids)
print('encoded userID : ', user_to_user_encoded)
print('encoded angka ke userID: ', user_encoded_to_user)

"""### Membagi Dataset Training dan Validasi"""

# Mengacak dataset
df = df.sample(frac=1, random_state=42)
df

from sklearn.model_selection import train_test_split

# -----------------------------
# 1. Siapkan matriks fitur & target
# -----------------------------
X = df[['user', 'product', 'interaction_score']].values.astype(np.float32)

# Skala rating ke 0–1  ➜ lebih stabil untuk training neural/embedding
min_rating = df['rating'].min()
max_rating = df['rating'].max()
y = df['rating'].astype(np.float32)
y_scaled = ((y - min_rating) / (max_rating - min_rating)).values  # ndarray float32

# -----------------------------
# 2. Train / Validation split (80 : 20)
# -----------------------------
X_train, X_val, y_train, y_val = train_test_split(
    X,
    y_scaled,
    test_size=0.20,
    random_state=42,
    shuffle=True
)

print(f"Ukuran train : {X_train.shape[0]}")
print(f"Ukuran valid : {X_val.shape[0]}")

"""## **Modeling**"""

# --------------------------------------------------
# 3. MODEL DEFINITION
# --------------------------------------------------
class RecommenderNet(tf.keras.Model):
    def __init__(self, num_users, num_products, embed_size=50, **kwargs):
        super().__init__(**kwargs)

        # ➤ user & product embeddings + bias
        self.user_embedding = layers.Embedding(
            num_users, embed_size,
            embeddings_initializer="he_normal",
            embeddings_regularizer=keras.regularizers.l2(1e-6)
        )
        self.user_bias = layers.Embedding(num_users, 1)

        self.product_embedding = layers.Embedding(
            num_products, embed_size,
            embeddings_initializer="he_normal",
            embeddings_regularizer=keras.regularizers.l2(1e-6)
        )
        self.product_bias = layers.Embedding(num_products, 1)

        # ➤ bobot learnable untuk interaction_score (scalar)
        self.interaction_weight = self.add_weight(
            name="interaction_weight",
            shape=(1,),
            initializer="he_normal",
            trainable=True
        )

    def call(self, inputs):
        # inputs: [user_id, product_id, interaction_score]
        user_id = tf.cast(inputs[:, 0], tf.int32)
        product_id = tf.cast(inputs[:, 1], tf.int32)
        interaction = tf.expand_dims(inputs[:, 2], axis=1)  # shape (batch,1)

        # embeddings & bias
        user_vec = self.user_embedding(user_id)
        prod_vec = self.product_embedding(product_id)
        user_b = self.user_bias(user_id)
        prod_b = self.product_bias(product_id)

        # dot-product user × product
        dot = tf.reduce_sum(user_vec * prod_vec, axis=1, keepdims=True)

        # skor akhir + kontribusi interaction_score
        x = dot + user_b + prod_b + self.interaction_weight * interaction

        return tf.nn.sigmoid(x)  # skala [0,1]

# --------------------------------------------------
# 3. COMPILE
# --------------------------------------------------
model = RecommenderNet(num_users, num_products, embed_size=50)

model.compile(
    loss=tf.keras.losses.BinaryCrossentropy(),
    optimizer=keras.optimizers.Adam(learning_rate=1e-3),
    metrics=[tf.keras.metrics.RootMeanSquaredError(name="rmse")]
)

model.summary()

# --------------------------------------------------
# 4. TRAINING
# --------------------------------------------------

history = model.fit(
    x=X_train,
    y=y_train,
    batch_size=8,
    epochs=100,
    validation_data=(X_val, y_val),
    verbose=2
)

"""### Visualisasi Metrik"""

metrics = history.history           # dict {'loss', 'val_loss', 'rmse', 'val_rmse', ...}

# ── Loss (Binary-Crossentropy) ──
plt.figure()
plt.plot(metrics['loss'],     label='Train Loss')
plt.plot(metrics['val_loss'], label='Val Loss')
plt.xlabel('Epoch')
plt.ylabel('Binary Crossentropy')
plt.title('Training vs Validation Loss')
plt.legend()
plt.show()

# ── RMSE ──
plt.figure()
plt.plot(metrics['rmse'],     label='Train RMSE')
plt.plot(metrics['val_rmse'], label='Val RMSE')
plt.xlabel('Epoch')
plt.ylabel('RMSE')
plt.title('Training vs Validation RMSE')
plt.legend()
plt.show()

"""Perhatikanlah, proses training model cukup smooth dan model konvergen pada epochs sekitar 100. Dari proses ini, kita memperoleh nilai error akhir sebesar sekitar 0.065 dan error pada data validasi sebesar 0.33. Nilai tersebut cukup bagus untuk sistem rekomendasi. Mari kita cek, apakah model ini bisa membuat rekomendasi dengan baik?"""

# --------------------------------------------------
# ➤ 0. SETTINGS
# --------------------------------------------------
TOP_N = 10          # banyak rekomendasi yang ingin ditampilkan
TOP_K = 5           # banyak produk favorit user yang ingin di‐list

# --------------------------------------------------
# ➤ 1. PILIH 1 USER (bisa random atau ditentukan manual)
# --------------------------------------------------
user_id = df['customer_id'].sample(1).iloc[0]             # random
# user_id = '…'  # ← kalau mau fix

user_name = (
    df.loc[df['customer_id'] == user_id, 'full_name']
      .dropna()
      .unique()
)
user_name = user_name[0] if len(user_name) else user_id[:8]  # fallback

print(f"Showing recommendations for user: {user_name}")
print('=' * 30)

# --------------------------------------------------
# ➤ 2. PRODUK YANG SUDAH DIRATING USER
# --------------------------------------------------
visited_mask  = df['customer_id'] == user_id
visited_df    = df[visited_mask]

# list (encoded) semua produk yang belum dikunjungi
all_items_enc    = set(product_to_product_encoded.values())
visited_items_enc = set(visited_df['product'].unique())
not_visited_enc   = list(all_items_enc - visited_items_enc)

# array [user_enc, product_enc, interaction_score=0] untuk produk yang belum dikunjungi
user_enc = user_to_user_encoded[user_id]
user_notvisit_arr = np.hstack([
    np.full((len(not_visited_enc), 1), user_enc, dtype=np.int32),
    np.array(not_visited_enc, dtype=np.int32).reshape(-1, 1),
    np.zeros((len(not_visited_enc), 1), dtype=np.float32)      # interaction = 0
])

# --------------------------------------------------
# ➤ 3. PREDIKSI & AMBIL TOP-N
# --------------------------------------------------
ratings_pred = model.predict(user_notvisit_arr, verbose=0).flatten()

top_idx          = ratings_pred.argsort()[-TOP_N:][::-1]
recommended_enc  = [not_visited_enc[i] for i in top_idx]
recommended_prod = [product_encoded_to_product[i] for i in recommended_enc]

# --------------------------------------------------
# ➤ 4. TAMPILKAN PRODUK YANG TELAH DIRATING USER (maks 10)
# --------------------------------------------------
print('Produk yang telah dirating oleh user')
print('-' * 30)

rated_user_items = (
    visited_df.sort_values(by='rating', ascending=False)
              .head(10)
)

for row in rated_user_items.itertuples():
    prod_name = row.product_name
    cat = row.product_category
    score = row.rating
    print(f"• {prod_name} ({cat}) — rating: {score}")

# --------------------------------------------------
# ➤ 5. TAMPILKAN TOP-N REKOMENDASI
# --------------------------------------------------
print('-' * 30)
print(f'Top {TOP_N} product recommendations')
print('-' * 30)

for rank, prod_name in enumerate(recommended_prod, 1):
    cat = df.loc[df['product_name'] == prod_name, 'product_category'].iloc[0]
    print(f"{rank}. {prod_name}  ({cat})")